### PR TITLE
add support to configure logging format

### LINKED ISSUE #97: support JSON log format for liveness-probe
- Provide a flag to enable JSON log formatting. 

We do this today for CSI driver implementations but the same can't be configured for `liveness-probe`. This can be done by adding `log-format-json=true` flag to the liveness-probe and setting the log format based on that.

### PR DESCRIPTION
**Pull request by aramase**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind feature

**What this PR does / why we need it**:
Adds configuration for json log formatter

**Which issue(s) this PR fixes**:

Fixes #97 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
added --log-format-json=<true | false> set log formatter to json (default: false)
```

### CODE REVIEW

**Comment by Jiawei0227** [comment]
Can you help to rebase this?

**Comment by aramase** [comment]
> Can you help to rebase this?

Done!

**Comment by pierluigilenoci** [comment]
@aramase could you please fix the conflicts?

**Comment by pierluigilenoci** [comment]
@aramase any feedback from the community?
Ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/442#issuecomment-777588848

**Comment by pierluigilenoci** [comment]
@aramase sorry if I disturb you but this PR seems a little abandoned.

**Comment by verult** [comment]
Hi @aramase , I'm working on the next release of livenessprobe. Do you happen to have any updates on this PR?

**Comment by aramase** [comment]
@verult If we want to include this in the next release, I can dust off the PR again. There has been some conversation on how to approach this: https://github.com/kubernetes-csi/node-driver-registrar/pull/129.

**Comment by msau42** [comment]
I believe @pohly was starting to look into structured logging for the csi sidecars.

**Comment by aramase** [comment]
> I believe @pohly was starting to look into structured logging for the csi sidecars.

Ah, gotcha! @pohly Let me know how I can help. With structured logging, we should still be able to support json log format.

**Comment by verult** [comment]
@aramase @msau42 @pohly my understanding from kubernetes-csi/node-driver-registrar#129 is that even with structured logging, we still need to add json logging separately. Does json logging depend on the structured logging work? Do you think either structured logging or json logging would be able to land for this current sidecar release cycle?

**Comment by pohly** [comment]
We should start an issue about structured logging where discuss all related aspects (configuration, log calls, how to pass a logger). This isn't specific to a certain sidecar.

@msau42: would that be worth a separate project under https://github.com/orgs/kubernetes-csi/projects?

**Comment by msau42** [comment]
> We should start an issue about structured logging where discuss all related aspects (configuration, log calls, how to pass a logger). This isn't specific to a certain sidecar.
> 
> Michelle Au: would that be worth a separate project under https://github.com/orgs/kubernetes-csi/projects?

Yeah that sounds good to me! Agree that we want to be consistent across sidecars and also consistent with the Kubernetes effort.

**Comment by verult** [comment]
Ack, since this requires a wider effort we'll leave it out of this release. Thanks all!

**Comment by pohly** [comment]
> would that be worth a separate project under https://github.com/orgs/kubernetes-csi/projects?

I created https://github.com/orgs/kubernetes-csi/projects/46. Let's discuss in one of the upcoming CSI standup meetings.

**Comment by pierluigilenoci** [comment]
@aramase could you please fix the PR?

**Comment by pohly** [comment]
/hold

Let's not merge this without aligning on a common direction for all sidecars first. See https://github.com/orgs/kubernetes-csi/projects/46 for a list of TODOs.

**Comment by pierluigilenoci** [comment]
This is still an issue

**Comment by pierluigilenoci** [comment]
@aramase could you please take a look?

**Comment by aramase** [comment]
@pierluigilenoci I will let the maintainers of the node-driver-registrar and liveness probe decide how they want to proceed with supporting json log formatting. I don't have the time currently for rebasing the 2 PRs, so I'm going to close them and let someone else pick up the issue if there is interest in supporting the json log format.

/close

**Pull request closed without merging**
