### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by sbezverk**
Updating CSI to 0.3.0 annd testing travis
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

### CODE REVIEW

**Comment by sbezverk** [comment]
@saad-ali I updated dependency to csi 0.3.0, let me know what exactly needed to close #13

**Comment by sbezverk** [comment]
@jsafrane looks like it is passing now.

**Comment by sbezverk** [comment]
@jsafrane @saad-ali  I added unit test and e2e positive and negative tests, PTAL

**Comment by sbezverk** [comment]
@jsafrane done PTAL

**Comment by jsafrane** [comment]
Commit message "Code changes" is not very useful, but for this time...

/lgtm

**Pull request merged**
