### PR TITLE
Fixes broken link contributor cheat sheet

### LINKED ISSUE #161: Broken Link of `contributor cheat sheet` need to fix
## Bug Report

I have observed same kind of issue in various kubernetes-csi project.
this happens because after the localization there are too much modifications done in the various directories.
I have observed same issue in [this ](https://github.com/kubernetes-csi/livenessprobe/blob/master/CONTRIBUTING.md) page also.

It has one broken link of the `contributes  cheat sheet` which needs to fix.
I will try to look in further csi repo as well and try to fix it as soon as I can

/kind bug
/assign

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #161

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
Please squash the changes

**Comment by amolmote** [comment]
Sure

**Comment by mauriciopoppe** [comment]
For the trivy presubmit failure I think we need to wait for https://github.com/kubernetes-csi/livenessprobe/pull/164 to be merged, then a force pushed commit should help retrigger it.

**Comment by amolmote** [comment]
You mean an empty commit on same branch

**Comment by Kartik494** [comment]
> You mean an empty commit on same branch

yeah so you can do is `git commit --amend --no-edit`
and then you can push as `git push orign <branchname> --force`

**Comment by amolmote** [comment]
> > You mean an empty commit on same branch
> 
> yeah so you can do is `git commit --amend --no-edit` and then you can push as `git push orign <branchname> --force`
thanks @Kartik494

**Comment by amolmote** [comment]
done @Kartik494

**Comment by Kartik494** [comment]
@amolmote Thanks for the updates ,  trivy job seems to be passed here , let other reviewers take a look at this also.
/lgtm

**Pull request merged**
